version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000" # host:container
    volumes:
      - .:/usr/src/app
    # command: bundle exec jekyll serve --host 0.0.0.0 --port 4000
    # command: /bin/sh -c "npm run build && bundle exec jekyll serve --host 0.0.0.0 --port 4000"
    command: /bin/sh -c "npm run build && bundle exec jekyll serve --host 0.0.0.0 --port 4000"
    # command: /bin/sh -c "bundle install && npm run build && bundle exec jekyll serve --host 0.0.0.0 --port 4000"
    